baseURL: "https://cneverett.github.io" 
title: Christopher Everett
theme: PaperMod
sitename: Christopher Everett

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

#taxonomies:
#    tag: tags

# menu:
#     main:
#         - name: Books
#           url: books/
#           weight: 5 
#         - name: Papers
#           url: papers/
#           weight: 2
#         - name: Courses
#           url: courses/
#           weight: 3
#         - name: Data
#           url: data/
#           weight: 4 

params:
    description: "This is the personal website for Christopher Everett"
    author: Christopher Everett
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "August 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: []
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Christopher Everett
          subtitle: "I am a D.Phil. student working in the Astrophysics sub-department of the University of Oxford under the supervision of Prof. Garret Cotter. My research pertains to mesoscopic modelling of astrophysical jets, that is to say modelling that includes both macro-scale physics of jet and spacetime structure and micro-scale physics of particle interactions all in one self-consistent package. To do this I have developed Diplodocus.jl (click the little dinosaur below), a framework through which to conduct this modelling. I am currently exploring how the inclusion of both micro- and macro-effects can alter our perspective on observations from jetted sources such as blazar. I also have interests in the field of advanced spacecraft propulsion - developing system inspired by astrophysical particle acceleration to accelerate humanity into the stars."
          imageUrl: "picture.jpg"
          imageWidth: 200
          imageHeight: 200
          #buttons:
          #  - name: Papers
          #    url: papers/

    socialIcons:

        - name: Email
          url: mailto:christopher.everett@physics.ox.ac.uk
        - name: CV
          url: cv.pdf
        - name: GitHub
          url: https://github.com/cneverett
        - name: orcid
          url: https://orcid.org/0000-0001-5181-108X
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=qapYZGkAAAAJ&hl
        - name: "diplodocus"
          url: https://cneverett.github.io/Diplodocus.jl/


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Christopher Everett"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
